version: "3.9"

services:
  mariadb:
    image: debian:bookworm
    build: ./requirements/mariadb
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - /home/herakoto/data:/var/lib/mysql

secrets:
  db_root_password:
    file: /home/herakoto/Inception/secrets/root_db_passwd
  db_user_password:
    file: /home/herakoto/Inception/secrets/user_db_password
